image:
#  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Release
#  - Debug

platform:
  - Win32
  - x64

# shallow_clone doesn't seem to work well with sub-repo.
# shallow_clone: true

init:
  - echo APPVEYOR_BUILD_WORKER_IMAGE = "%APPVEYOR_BUILD_WORKER_IMAGE%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set GENERATOR=Visual Studio 15 2017)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (set GENERATOR=Visual Studio 14 2015)
  - echo PLATFORM = "%PLATFORM%"
  - if "%PLATFORM%"=="x64" (set GENERATOR=%GENERATOR% Win64)
  - echo GENERATOR = "%GENERATOR%"

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G "%GENERATOR%"

build:
  project: build\euler.sln

test_script:
  - ctest -C %CONFIGURATION%
